kind: semantics

metadata:
  name: feishu-mirror-semantics
  version: 1.0.0
  description: >
    Catalog overlay for the Feishu mirror. Each table here is populated by
    a sync script driving lark-cli, not by direct user INSERTs — so the
    column descriptions read like a downstream-of-API contract rather than
    a hand-curated schema. Regenerated by setup_feishu.py; hand-curated
    overlays may live in semantics/ next to this file and will be merged.

spec:
  sources:
    - name: feishu
      description: >
        SQLite mirror of Lark/Feishu workspaces. Rows arrive via lark-cli
        (`base +record-list`, `sheets +read`) and are normalised by
        scripts/sync_*.py. Schema is intentionally generic — a per-record
        JSON blob plus an EAV-style cell table — so the same mirror can
        absorb arbitrary Bitables without per-table DDL.
      tables:
        - name: feishu_bitable_records
          description: >
            One row per Bitable record. fields_json carries the full record
            payload as returned by `lark-cli base +record-list` so any
            field — including formula / lookup / attachment — round-trips
            losslessly. Use json_extract(fields_json, '$."<field_id>"') to
            pull a specific cell when the JSON1 extension is loaded.
          columns:
            - name: base_token
              description: "Bitable Base id (also called app_token in API URLs)."
            - name: table_id
              description: "Table id within the Base — schema unit."
            - name: record_id
              description: "Stable Lark record id; primary key inside one table."
            - name: fields_json
              description: "Whole record as JSON; keys are field_id, values are typed cells."
            - name: synced_at
              description: "ISO-8601 timestamp written by sync_bitable.py at the end of each pull."
        - name: feishu_bitable_fields
          description: >
            Schema rows for every (base_token, table_id) the user has
            synced. Mirrors `lark-cli base +field-list`. Drives the
            describe-feishu-source pipeline.
          columns:
            - name: base_token
              description: "Bitable Base id."
            - name: table_id
              description: "Table id."
            - name: field_id
              description: "Stable column id (matches keys inside fields_json)."
            - name: field_name
              description: "Human-readable column name as shown in the Bitable UI."
            - name: field_type
              description: "Lark field-type integer code; see references/schema_mapping.md for the lookup table."
            - name: is_primary
              description: "1 if this column is the Base's primary key column, else 0."
            - name: description
              description: "Optional column description set inside the Bitable UI."
        - name: feishu_sheet_cells
          description: >
            One row per cell of a synced spreadsheet range. Wide/sparse
            sheets stay sparse — only non-null cells are stored.
          columns:
            - name: spreadsheet_token
              description: "Lark spreadsheet token (the long id in the share URL)."
            - name: sheet_id
              description: "Sheet (tab) id within the spreadsheet."
            - name: row_idx
              description: "0-based row index within the synced range."
            - name: col_idx
              description: "0-based column index within the synced range."
            - name: value_text
              description: "Text rendering of the cell — always populated."
            - name: value_number
              description: "Numeric value if Lark reported the cell as a number, else NULL."
        - name: feishu_sync_log
          description: >
            Append-then-upsert ledger of sync runs. The agent reads this to
            decide whether a refresh is needed and to surface stale data.
          columns:
            - name: source_type
              description: "'bitable' or 'sheet'."
            - name: source_key
              description: "Composite id: '<base_token>/<table_id>' for Bitable, '<spreadsheet_token>/<sheet_id>' for Sheet."
            - name: last_synced_at
              description: "ISO-8601 timestamp of the most recent successful or failed run."
            - name: row_count
              description: "Number of rows pulled in the last successful run."
            - name: status
              description: "'ok' or 'err: <message>' — failed runs leave the previous data in place."
